// Postman Application Configuration
// Generated by `postman application init`
//
// Docs: https://learning.postman.com/docs/postman-cli/postman-cli-options/

module.exports = {
    // The command to run before analysis (e.g. your test suite).
    command: 'npm test',

    // Targets define which collections and environment to use for analysis.
    // Select a target at runtime with: postman application test --target <name>
    targets: {
        default: {
            environment: 'local',
            collections: [
                'api.practicesoftwaretesting.com',
            ],
        },
        beta: {
            environment: 'staging',
            collections: [
                'api.practicesoftwaretesting.com',
            ],
        },

        // Example: a production target
        // production: {
        //     environment: 'Production',
        //     collections: [
        //         'My Collection',
        //     ],
        // },
    },

    // Filters exclude matching network requests from analysis.
    // A request is dropped if it matches any rule below.
    // アナリティクス/トラッキング系はクエリパラメータが長くファイル名長制限(ENAMETOOLONG)
    // を超えてキャプチャ保存が失敗するため除外する
    filters: {
        urlPatterns: [
            'google-analytics\\.com',
            'googletagmanager\\.com',
            'cloudflareinsights\\.com',
            '\\.css$',
            '\\.svg$',
            '\\.png$',
            '\\.jpg$',
            '\\.woff2?$',
        ],
        methods: [],
        headers: {},
    },

    // Transformers rewrite proxied requests back to their real upstream URLs
    // so that captured traffic can be matched against your Postman collections.
    //
    // When your app routes API calls through a gateway or proxy, the captured
    // URL is the gateway URL — not the real service URL. Each transformer entry
    // lets you reverse that mapping:
    //
    //   url              – prefix string or RegExp to match the transformer URL.
    //   transformRequest  – receives the raw request body and returns
    //                       { url, method } pointing to the real service.
    //   transformResponse – (optional) unwraps the transformer response envelope
    //                       so assertions see the real payload.
    //
    // transformers: [
    //     {
    //         url: 'https://api-gateway.example.com/proxy',
    //
    //         transformRequest (body) {
    //             var parsed = typeof body === 'string'
    //                 ? JSON.parse(body) : (body || {});
    //
    //             return {
    //                 url: 'https://' + parsed.service + '.internal.example.com' + parsed.path,
    //                 method: (parsed.method || 'GET').toUpperCase(),
    //             };
    //         },
    //
    //         transformResponse (response) {
    //             if (response && typeof response === 'object' && 'data' in response) {
    //                 return response.data;
    //             }
    //
    //             return response;
    //         },
    //     },
    // ],
};
